### ISSUE TITLE
"node index.js" breaks with 'Error: Cannot find module 'onoff''

### ISSUE THREAD

**Issue by stolj** [cristianpb/snipshandler#4]
Hi,

first of all, thanks a lot for the great work. I was trying to replicate this with a seed/snips development kit.

After installing dependance packages 'nodejs' and 'npm', I get:

pi@snips-base ~/src/snipshandler
$ make up
ls: cannot access '/home/pi/src/snipshandler/conf/assistant_*.zip': No such file or directory
media
node index.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'onoff'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/src/snipshandler/relay.js:1:76)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Makefile:16: recipe for target 'up' failed
make: *** [up] Error 1

Any help would be highly appriciated.

**Comment by stolj** [comment]
resolved of course via

  $ npm install onoff
